### PR TITLE
Bestpractice: mention OSHP Validator

### PR DESCRIPTION
**Pull request by ecki**
Let me know if I should complete remove the mentioning of the gist, or if we should add the actual git clone commands?

### CODE REVIEW

**Review by righettod — APPROVED** [review]

**Comment by righettod** [comment]
Hi,
Nice catch 😃 
Thank you very much for the PR!!!
@riramar You can merge it if it is OK for you too 😃

**Comment by ecki** [comment]
I just noticed the yml file name has changed, should we add a new sample command run, with git clone? Do you want to keep the gist comment?

**Comment by righettod** [comment]
Hi @ecki ,

Nice catch again 😃 

You can submit a PR to update the name if it is possible on your side.

Thank you very much in advance 👍

**Comment by righettod** [comment]
I will handle it in my next PR

**Comment by righettod** [comment]
See https://github.com/OWASP/www-project-secure-headers/pull/88

**Pull request merged**
