### PR TITLE
Add Permissions-Policy header

### PR DESCRIPTION
**Pull request by righettod**
Handle issue #37

### CODE REVIEW

**Comment by righettod** [comment]
Check ink error was a false-positive.

`https://gf.dev/cross-domain-policy-test` is active

image

**Comment by riramar** [comment]
Here it's saying "All checks have failed".
Could you please check and let me know?

**Comment by righettod** [comment]
image

image

"**All checks have failed**" is because there is only one check in the list and it has failed (false positive) 😃 

So it's OK here 😃

**Comment by riramar** [comment]
Thanks for the explanation!

**Comment by righettod** [comment]
You are welcome, thanks a lot for the merge 😃

**Pull request merged**
