### PR TITLE
Add a new tab with extra info.

### PR DESCRIPTION
**Pull request by righettod**
Hi,

This PR add a new *misc* tab providing extra information about HTTP security headers in general. 

The OSHP is focused on HTTP Security **Response** headers but some **Request** header like `Sec-Fetch-*` ([source](https://developer.mozilla.org/en-US/docs/Glossary/Fetch_metadata_request_header)) can be useful to know from a defensive point of view.

I have proposed a new dedicated tab in order to not distrub the global content stucture and cause any confusion on the reader side.

Thanks in advance 😃

### CODE REVIEW

**Comment by righettod** [comment]
I'm not the root cause of the link check failure 😃 

image

**Comment by righettod** [comment]
image

**Comment by riramar** [comment]
Hi @righettod

Probably the GitHub actions are missing some request headers.
As you can see below curl it's returning 403 and browser 200.
Can you check the missing request headers?

image

image

**Comment by righettod** [comment]
Hi, ok I will do it.

**Comment by righettod** [comment]
I have checked the new  config added and the headers defined are correctly added:

image

I have remarked that a  **HEAD** is sent prior a **GET**:

image

However, HEAD is accepted using CURL:

image

I need to dig deeper because I do not understand the source of the **503**...

**Comment by riramar** [comment]
Was it the user-agent only?

**Comment by riramar** [comment]
I though this would solve the issue but it didn't so I reverted back.
It seems to be the user-agent request header the problem.

image

**Comment by righettod** [comment]
With the revert you have removed the entire content of the contrib :(

**Comment by righettod** [comment]
I will submit a new PR with the content

**Comment by righettod** [comment]
See #41

**Comment by riramar** [comment]
I though the link validations was supposed to block any future changes.
Since the links were still breaking I decided to revert everything.
I'll check your new PR.

**Comment by righettod** [comment]
No problem, in fact you done the right thing. Indeed, it allow me to
perform a clean new PR and have a clear view of the issue. Thank again for
your help and support on this PR and matter :)

**Pull request merged**
