### PR TITLE
Update info.md

### PR DESCRIPTION
**Pull request by rfc-st**
Add another HTTP headers analyzer.

### CODE REVIEW

**Comment by righettod** [comment]
Hi,

Thanks for the PR.

@riramar I think that we should drop this part in pink:

image

Indeed, tools have a dedicated tab and, here, the PR #74 add the present tool to the list.

**Comment by riramar** [comment]
> Hi,
> 
> Thanks for the PR.
> 
> @riramar I think that we should drop this part in pink:
> 
> image
> 
> Indeed, tools have a dedicated tab and, here, the PR #74 add the present tool to the list.

can you send a PR to remove it?

**Comment by righettod** [comment]
Thank you 😃

**Comment by righettod** [comment]
Yes it's OK 👍

**Pull request merged**
