### PR TITLE
Add new headers to remove/icons/fix typos

### PR DESCRIPTION
**Pull request by righettod**
Hi,

This PR add a new header to remove as well as fixing a typo in a menu name and add icons.

Thanks in advance 😃

### CODE REVIEW

**Comment by riramar** [comment]
Thanks!

**Comment by dstrzelec** [comment]
@righettod you appear to have added our domain name in this commit. See line 161. Can you remove it please?

**Comment by righettod** [comment]
@dstrzelec I will do it.

**Comment by dstrzelec** [comment]
Then you.

**Pull request merged**
