### PR TITLE
Add CORS section

### PR DESCRIPTION
**Pull request by righettod**
Hi,

This PR add a new section, in the **Best Practices** tab, regarding the configuration of the CORS headers .

🤝 @riramar I need your help to review my proposal and ensure that my content is accurate, helpful and does not any technical mistake.

📋 It is a work on this [issue](https://github.com/oshp/oshp-tracking/issues/19).

Thank you a lot for your help 👍

### CODE REVIEW

**Comment by riramar** [comment]
Hi @righettod 

Thanks for sending this PR. CORS for sure it's something we need to improve in our OWASP project.
I'm on vacation right now, so I'll review your PR probably during next week.
Meanwhile I'd recommend you to check the posts about CORS from here https://jub0bs.com/posts/. Julien Cretel has provided amazing content regarding CORS security.

Best regards,
Ricardo Iramar

**Comment by righettod** [comment]
Hi @riramar ,

Take the time you need and do it when you have spare time for it. I will take a close look at the site your mentioned to see what content I can get.

Enjoy your vacation 😃

**Comment by riramar** [comment]
Thanks @righettod !

**Comment by righettod** [comment]
You are welcome, thanks a lot for your review 👍

**Pull request merged**
