### PR TITLE
Add COEP / COOP / CORP headers

### PR DESCRIPTION
**Pull request by righettod**
Hi,

This PR cover the issue #6 .

Thanks a lot in advance 😃

### CODE REVIEW

**Comment by righettod** [comment]
I will group headers, just let me few minutes 😃

**Comment by righettod** [comment]
Done, deprecated headers grouped.

**Comment by riramar** [comment]
Thanks a lot for your contribution! 👍

**Comment by righettod** [comment]
You are welcome, thank you for this project

**Pull request merged**
