### PR TITLE
Handle dead and not clickable links

### PR DESCRIPTION
**Pull request by righettod**
Hi,

This PR is related to this [discussion](https://github.com/OWASP/www-project-secure-headers/issues/15#issuecomment-782067673).

Precisely it:
* Fix dead links.
* Try the `<url>` syntax in order to tackle not clickable links once converted by jekyll.

### CODE REVIEW

**Comment by righettod** [comment]
Close it because here is a error in my branch

**Comment by righettod** [comment]
OK will wait that you merge the #24 and I submit another one after to handle the dead links.

**Comment by righettod** [comment]
I have reopened it because now it's OK 😃

**Comment by riramar** [comment]
The merge failed in just one item. Could you please check?

image

**Comment by righettod** [comment]
OK i'm on it :)

**Comment by riramar** [comment]
https://github.com/request/request/issues/2738

Seems some sites reject the connection if the request is missing some standard headers.
The fix would need to change gaurav-nelson/github-action-markdown-link-check which is not in our control.
We could mirror but I don't have time to manage a mirror right now.

Could you please go ahead and remove this https://cyh.herokuapp.com/cyh from Technical Resources tab?
Another question, when this check fails this will totally stop the deploy of the pages? Sorry, I'm not really familiar with this process.

**Comment by righettod** [comment]
I will handle it asap :)

**Comment by righettod** [comment]
> Could you please go ahead and remove this https://cyh.herokuapp.com/cyh from Technical Resources tab?

PR #26 proposed for the removal 😃 

> The fix would need to change gaurav-nelson/github-action-markdown-link-check which is not in our control. We could mirror but I don't have time to manage a mirror right now.

I propose to see if we have still issues with new coming links and if it's the case then I will search another way to check the links because forking the repository will force us to maintain the repository for a small difference. If we have issues with new links, I will also see to make a PR to the source repository to add control over headers...

> Another question, when this check fails this will totally stop the deploy of the pages? Sorry, I'm not really familiar with this process.

Never be sorry to ask a question, we are here to exchange knowledge between us in a cool way in order to let everyone grow 💯 

Actually, if a link is broken, the workflow fail but as the deployment is not performed by the workflow itself, I don't know if it stops the deployment. We can make a test to get the response 😄 

In all cases, it is possible to set up the workflow to not fail is a broken link is found. 

My opinion on this is that it is a good idea to break the workflow because it allows to:
- Ensure that every PR add valid links.
- Same for direct commit on the master branch.
- Ensure, in case of the deployment is stopped, that when the site is published then all links are valid.

Feel free to ask me if something is not clear 😃

**Comment by riramar** [comment]
Thanks for explanation and I agree to keep this broken link check as a blocker so as you said it'll ensure that every PR add valid links only. 😃 
Can I add your name under Contributors (https://owasp.org/www-project-secure-headers/)? If yes do you want to point the link to your email or an URL?
I totally agree with you regarding asking questions and probably you already know this quote below.

“The man who asks a question is a fool for a minute, the man who does not ask is a fool for life.”
― Confucius

**Comment by righettod** [comment]
Very nice quote, I was not aware of this, so now I am thank to you 😃 

Regarding adding my name, it is ok and I thank you very much a lot, you can add a link to my home page https://righettod.eu

I will take a look at the issue with the table rendering in one character...I kept you informed via the dedicated issue 👍

**Comment by riramar** [comment]
Just include your name. Thanks a lot for the contributions!

**Pull request merged**
